language: cpp
compiler:
  - clang
  # - gcc don't really care

os:
  - linux
  - osx    # beta only

# Run setup to build ninja/gyp/etc and actually build xenia.
before_script:
  - travis_retry ./xenia-build.py setup
  #- ./xenia-build.py build --debug
  - ./third_party/ninja/ninja -C build/xenia/Debug alloy-test

# Run test suite.
script:
  - ./build/xenia/Debug/alloy-test
  #- ./test/run-tests.sh
